// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hack4good.Infrastructure;

#nullable disable

namespace hack4good.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HackContext))]
    [Migration("20221007224119_Role")]
    partial class Role
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hack4good.DAL.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c040c031-c485-4925-942a-c7cdbef231fa"),
                            IsAdmin = true,
                            Login = "admin",
                            Password = "admin"
                        },
                        new
                        {
                            Id = new Guid("7d0f8501-a76c-4f1c-90ad-5ef95b93dee1"),
                            IsAdmin = false,
                            Login = "user",
                            Password = "user"
                        });
                });

            modelBuilder.Entity("hack4good.DAL.TokenSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("TokenSession");
                });

            modelBuilder.Entity("hack4good.DAL.TokenSession", b =>
                {
                    b.HasOne("hack4good.DAL.Account", "Account")
                        .WithMany("TokenSessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("hack4good.DAL.Account", b =>
                {
                    b.Navigation("TokenSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
